package edu.nps.moves.dismobile;

import java.util.*;
import java.io.*;
import edu.nps.moves.disenum.*;
import edu.nps.moves.disutil.*;


/**
 * 5.3.7.4.1: Navigational and IFF PDU. COMPLETE
 *
 * Copyright (c) 2008-2014, MOVES Institute, Naval Postgraduate School. All rights reserved.
 * This work is licensed under the BSD open source license, available at https://www.movesinstitute.org/licenses/bsd.html
 *
 * @author DMcG
 */
public class IffAtcNavAidsLayer1Pdu extends DistributedEmissionsFamilyPdu implements Serializable
{
   /** ID of the entity that is the source of the emissions */
   protected EntityID  emittingEntityId = new EntityID(); 

   /** Number generated by the issuing simulation to associate realted events. */
   protected EventID  eventID = new EventID(); 

   /** Location wrt entity. There is some ambugiuity in the standard here, but this is the order it is listed in the table. */
   protected Vector3Float  location = new Vector3Float(); 

   /** System ID information */
   protected SystemID  systemID = new SystemID(); 

   /** padding */
   protected int  pad2;

   /** fundamental parameters */
   protected IffFundamentalData  fundamentalParameters = new IffFundamentalData(); 


/** Constructor */
 public IffAtcNavAidsLayer1Pdu()
 {
    setPduType( (short)28 );
 }

public int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   marshalSize = marshalSize + emittingEntityId.getMarshalledSize();  // emittingEntityId
   marshalSize = marshalSize + eventID.getMarshalledSize();  // eventID
   marshalSize = marshalSize + location.getMarshalledSize();  // location
   marshalSize = marshalSize + systemID.getMarshalledSize();  // systemID
   marshalSize = marshalSize + 2;  // pad2
   marshalSize = marshalSize + fundamentalParameters.getMarshalledSize();  // fundamentalParameters

   return marshalSize;
}


public void setEmittingEntityId(EntityID pEmittingEntityId)
{ emittingEntityId = pEmittingEntityId;
}

public EntityID getEmittingEntityId()
{ return emittingEntityId; 
}

public void setEventID(EventID pEventID)
{ eventID = pEventID;
}

public EventID getEventID()
{ return eventID; 
}

public void setLocation(Vector3Float pLocation)
{ location = pLocation;
}

public Vector3Float getLocation()
{ return location; 
}

public void setSystemID(SystemID pSystemID)
{ systemID = pSystemID;
}

public SystemID getSystemID()
{ return systemID; 
}

public void setPad2(int pPad2)
{ pad2 = pPad2;
}

public int getPad2()
{ return pad2; 
}

public void setFundamentalParameters(IffFundamentalData pFundamentalParameters)
{ fundamentalParameters = pFundamentalParameters;
}

public IffFundamentalData getFundamentalParameters()
{ return fundamentalParameters; 
}


public void marshal(DataOutputStream dos)
{
    super.marshal(dos);
    try 
    {
       emittingEntityId.marshal(dos);
       eventID.marshal(dos);
       location.marshal(dos);
       systemID.marshal(dos);
       dos.writeShort( (short)pad2);
       fundamentalParameters.marshal(dos);
    } // end try 
    catch(Exception e)
    { 
      System.out.println(e);}
    } // end of marshal method

public void unmarshal(DataInputStream dis)
{
     super.unmarshal(dis);

    try 
    {
       emittingEntityId.unmarshal(dis);
       eventID.unmarshal(dis);
       location.unmarshal(dis);
       systemID.unmarshal(dis);
       pad2 = (int)dis.readUnsignedShort();
       fundamentalParameters.unmarshal(dis);
    } // end try 
   catch(Exception e)
    { 
      System.out.println(e); 
    }
 } // end of unmarshal method 


/**
 * Packs a Pdu into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if buff is too small
 * @throws java.nio.ReadOnlyBufferException if buff is read only
 * @see java.nio.ByteBuffer
 * @param buff The ByteBuffer at the position to begin writing
 * @since ??
 */
public void marshal(java.nio.ByteBuffer buff)
{
       super.marshal(buff);
       emittingEntityId.marshal(buff);
       eventID.marshal(buff);
       location.marshal(buff);
       systemID.marshal(buff);
       buff.putShort( (short)pad2);
       fundamentalParameters.marshal(buff);
    } // end of marshal method

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if buff is too small
 * @see java.nio.ByteBuffer
 * @param buff The ByteBuffer at the position to begin reading
 * @since ??
 */
public void unmarshal(java.nio.ByteBuffer buff)
{
       super.unmarshal(buff);

       emittingEntityId.unmarshal(buff);
       eventID.unmarshal(buff);
       location.unmarshal(buff);
       systemID.unmarshal(buff);
       pad2 = (int)(buff.getShort() & 0xFFFF);
       fundamentalParameters.unmarshal(buff);
 } // end of unmarshal method 


 /*
  * The equals method doesn't always work--mostly it works only on classes that consist only of primitives. Be careful.
  */
@Override
 public boolean equals(Object obj)
 {

    if(this == obj){
      return true;
    }

    if(obj == null){
       return false;
    }

    if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public boolean equalsImpl(Object obj)
 {
     boolean ivarsEqual = true;

    if(!(obj instanceof IffAtcNavAidsLayer1Pdu))
        return false;

     final IffAtcNavAidsLayer1Pdu rhs = (IffAtcNavAidsLayer1Pdu)obj;

     if( ! (emittingEntityId.equals( rhs.emittingEntityId) )) ivarsEqual = false;
     if( ! (eventID.equals( rhs.eventID) )) ivarsEqual = false;
     if( ! (location.equals( rhs.location) )) ivarsEqual = false;
     if( ! (systemID.equals( rhs.systemID) )) ivarsEqual = false;
     if( ! (pad2 == rhs.pad2)) ivarsEqual = false;
     if( ! (fundamentalParameters.equals( rhs.fundamentalParameters) )) ivarsEqual = false;

    return ivarsEqual && super.equalsImpl(rhs);
 }
} // end of class
